// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/LiuKaHo/driverModule/dao/ent/order"
	"github.com/LiuKaHo/driverModule/dao/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescName is the schema descriptor for name field.
	orderDescName := orderFields[0].Descriptor()
	// order.DefaultName holds the default value on creation for the name field.
	order.DefaultName = orderDescName.Default.(string)
}
